## Analysis of survey data

Once a population level survey has been carried out, the fully specified data set will essentially consist of subject level records indicating demographic factors, cluster/stratum membership, and various clinical indicators such as final HIV status and recency status.

A cross sectional survey leads to a core dataset with typical (germaine to the present application) columns

* Subject ID (a meaningless serial number)
* Primary sampling unit (cluster ID)
* Weight (based on estimates of demographic/geographic structure)
* Stratum (an ID indicating strata such as age, rage, (rural/urban) settlement type,.. )
* Sex/Gender (no need to settle heated debates here - M/F will do)
* HIV status (0/1 for -/+ respectively)
* Recency Status (0/1 for Non-recent/Recent respectively)

The example data set provided is here @URL@. It has the specific column names corresponding to these, in CSV form:
* SID
* PSU
* W
* S
* G
* H
* R
(Null values are recorded as consecutive commas ??)

This will usually be processed by somewhat ad-hoc means, generalizable for certain standard sampling frame types.


To facilitate a (hopefully preliminary) 'naive' analysis, @the app@ has a ‘Counts based estimate’ box (on what tab?), which takes (or looks up from an uploaded data set) survey counts, and hence produces prevalence estimates (for both HIV and recent infection, including variances) under the simplifying assumption of individual level random selection of subjects from a single population group.

In the example data set, this leads to:

* N subjects tested for HIV
* N positive results, for an unweighted HIV prevalence of 20% estimated with a relative standard error of 2.8%
* N recent results, among N_RA recency ascertainments, for a prevalence of recent infection, amongst HIV positives, of 10%, with a relative standard error of 9%

We assume a recency test with
* an MDRI of 200 days estimated with a relative standard error of 5%
* an FRR of 5% estimated with a relative standard error of 20%
Which is provided in the fields of the ‘recency test’ box

This @triggered by refresh/button@ leads to an incidence estimation summary:

@insert here@

In order to accommodate arbitrarily sophisticated analysis of complex survey data sets, the conception of @the app@ is that a substantial layer of intermediate processing is expected, the result of which is to reduce the full survey data set to:

*	an estimate of HIV prevalence
*	an estimate of the prevalence of ‘recent infection’ amongst those who are HIV positive.
*	A variance/covariance matrix for these two prevalence estimates

While @the app@ has no firm requirements about how these estimates are to be obtained, they need to be provided in the specified form, either by hand into the interface, or by uploading a file - by which it is possible to provide estimates from multiple surveys in one transaction of the calculator.

From the same underlying data set that generated the counts just used above, we obtained
*	an estimate of HIV prevalence
*	an estimate of the prevalence of ‘recent infection’ amongst those who are HIV positive.
*	A variance/covariance matrix for these two prevalence estimates

which are entered into , ...

Using primarily the *inctools* Function `incprops`, @the app@ will report:

* the (user provided) HIV Prevalence, CI and (relative) standard error
* an incidence point estimate, confidence interval, and (relative) standard error
* the equivalent annualised risk of infection (which is usually numerically very similar)
* the correlation/covariance of HIV Prevalence and Incidence (including an approximate CI ?? REALLY ??)
* implied confidence intervals on MDRI and FRR derived from input parameters (PEs and RSEs)



## Key App features

### 
